name: dyniku
services:
  dyniku:
    image: ${DYNIKU_IMAGE:-ghcr.io/maroishiku/dyniku:0.1.0}
    container_name: dyniku
    hostname: dyniku
    restart: unless-stopped
    ports:
      - target: 8507
        published: "8507"
        protocol: tcp
    environment:
      - BACKUP_DIRECTORY=/data
      - BACKUP_PERIOD=0
      - HTTP_TIMEOUT=10s
      - ISHIKU_BACKUP_DIRECTORY=/data
      - ISHIKU_BASE_PATH=/
      - ISHIKU_CONFIG_FILE=/data/config.json
      - ISHIKU_DATA_DIR=/data
      - ISHIKU_LOG_LEVEL=info
      - ISHIKU_SETUP_SECRET_FILE=/run/secrets/ishiku_setup_secret
      - LISTENING_ADDRESS=:8507
      - LOG_CALLER=hidden
      - LOG_LEVEL=info
      - PERIOD=5m
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - ROOT_URL=/
      - UPDATE_COOLDOWN_PERIOD=5m
      - TZ=Europe/Berlin
    volumes:
      - type: bind
        source: /DATA/AppData/dyniku/data
        target: /data
      - type: bind
        source: /DATA/AppData/dyniku/secrets/setup_secret.txt
        target: /run/secrets/ishiku_setup_secret
        read_only: true
    labels:
      icon: https://raw.githubusercontent.com/MaroIshiku/dyniku/main/internal/server/ui/static/dyniku-logo.png
      title.en_us: Dyniku
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://raw.githubusercontent.com/MaroIshiku/dyniku/main/internal/server/ui/static/dyniku-logo.png
  index: /
  is_uncontrolled: false
  port_map: "8507"
  scheme: http
  store_app_id: dyniku
  title:
    custom: Dyniku
    en_us: Dyniku
