apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyniku
  labels:
    app: dyniku
spec:
  selector:
    matchLabels:
      app: dyniku
  template:
    metadata:
      labels:
        app: dyniku
    spec:
      containers:
        - name: dyniku
          image: ghcr.io/maroishiku/dyniku:0.3.0@sha256:4ed4741a1294281d4ede33a0345bd3abf624d0b2f5e65142b6a6c5a9b9575214
          envFrom:
            - secretRef:
                name: dyniku-config
          ports:
            - containerPort: 8507
