apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyniku
  labels:
    app: dyniku
spec:
  selector:
    matchLabels:
      app: dyniku
  template:
    metadata:
      labels:
        app: dyniku
    spec:
      containers:
        - name: dyniku
          image: ghcr.io/maroishiku/dyniku:latest
          envFrom:
            - secretRef:
                name: dyniku-config
          ports:
            - containerPort: 8000
